/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        src="https://unpkg.com/htmx.org@1.9.4"
      />
      <Script id="btn-loader" strategy="afterInteractive">
        {`
            document.querySelector('#click-btn')?.addEventListener('click', (e) => {
              const state = e.currentTarget.value === "blue" ? "red" : "blue"
              e.currentTarget.classList = "p-2 rounded-md bg-" + state + "-500";
              e.currentTarget.value = state;
            })
          `}
      </Script>
      <body>{children}</body>
    </html>
  );
}
